### ISSUE TITLE
how to get the remote ip?

### ISSUE THREAD

**Issue by jqiris** [Totodore/socketioxide#101]

**Comment by Totodore** [comment]
Currently you can't but it is on my to-do list. This issue can serve as a tracking issue for this feature

**Comment by DnaBoss** [comment]
Hi,

I'm interested in working on this issue. 
Do you have any specific suggestions or preferred approaches for tackling it?

Thanks!

**Comment by DnaBoss** [comment]
> Currently you can't but it is on my to-do list. This issue can serve as a tracking issue for this feature
Hi,

I'm interested in working on this issue.
Do you have any specific suggestions or preferred approaches for tackling it?

Thanks!

**Comment by Totodore** [comment]
As said before, there is no way to do that with socketioxide because it is not included in the tower/hyper spec. The way to get the IP is different between each HTTP framework. I will do a recap here for axum and close the issue:
## Axum
Use [`into_make_service_with_connect_info`](https://docs.rs/axum/latest/axum/struct.Router.html#method.into_make_service_with_connect_info) to create the server and later use the [`HttpExtension`](https://docs.rs/socketioxide/latest/socketioxide/extract/struct.HttpExtension.html) provided by socketioxide:
```rust
fn connect(s: SocketRef, client_ip: HttpExtension<ConnectInfo<SocketAddr>) {
  println!("client_ip: {:?}", client_ip);
}
```
