### ISSUE TITLE
Support for Sec-Websocket-Protocol

### ISSUE THREAD

**Issue by spoorn** [Totodore/socketioxide#341]
**Is your feature request related to a problem? Please describe.**

Support [`Sec-Websocket-Protocol`](https://datatracker.ietf.org/doc/html/rfc6455#section-11.3.4) header in websocket handshake so the server can define subprotocols it accepts.
[Some info on the header field](https://developer.mozilla.org/en-US/docs/Web/HTTP/Protocol_upgrade_mechanism#:~:text=specified%20key.-,Sec%2DWebSocket%2DProtocol,-The%20Sec%2DWebSocket)

**Describe the solution you'd like**

I'm not sure if it's expected to support this outside of `socketioxide/engineioxide`, such as directly via `axum`, but it seems socketioxide does the websocket upgrade in [ws.rs and the response to the client should contain the subprotocol accepted by the server](https://github.com/Totodore/socketioxide/blob/04f7ab3cde9fad9ede58d9c224f8dcd1db3c50d5/engineioxide/src/transport/ws.rs#L36-L96).  `SEC_WEBSOCKET_ACCEPT` is already there.

I would imagine a user would have some way to configure for the websocket server connections (e.g. subprotocols to support) when creating the SocketIO layer

**Comment by Totodore** [comment]
We could set the `Sec-Websocket-Protocol` and it could improve the compatbility with other engine.io clients. But it would be set to "engine.io" as it is the only sub protocol used with websocket. There is no way that the user would be able to manually set it because it would not respect the ws protocol spec.

If you want to support subprotocols over socket.io you can use the auth payload or query params.
