### ISSUE TITLE
Generate TypeScript types

### ISSUE THREAD

**Issue by musjj** [Totodore/socketioxide#397]
**Is your feature request related to a problem? Please describe.**
In the TypeScript implementation, you can share your backend types with the client (https://socket.io/docs/v4/typescript/#types-for-the-client):

```ts
interface ServerToClientEvents {
  noArg: () => void;
  basicEmit: (a: number, b: string, c: Buffer) => void;
  withAck: (d: string, callback: (e: number) => void) => void;
}

interface ClientToServerEvents {
  hello: () => void;
}
```

Then on the client:

```ts
const socket: Socket<ServerToClientEvents, ClientToServerEvents> = io();

// Everything is typed

socket.emit("hello");

socket.on("basicEmit", (a, b, c) => {
  // a is inferred as number, b as string and c as buffer
});
```

**Describe the solution you'd like**

It would be nice if we can generate these types from our Rust code. There's this nice library for generating TypeScript types from Rust: https://github.com/Aleph-Alpha/ts-rs

**Describe alternatives you've considered**
You could use `ts-rs` like mentioned above, but you'd need to manually assemble the types and adjust them everytime the Rust code is changed.

**Comment by Totodore** [comment]
This is completely impossible because the event name can't be moved to a type, we would need `&'static str` as const generic for that. And even with that it would imply to add a generic on all the library types which would drastically reduce ease of use. I'm closing the issue, but if someone wants to propose something (which I doubt is possible), I will reopen it.
