### ISSUE TITLE
Example for emitting messages from application logic

### ISSUE THREAD

**Issue by cr1tbit** [Totodore/socketioxide#60]
Hello,

I'm not experienced with rust so I must admit my defeat - I don't know how to asynchronously generate messages from the code logic. 

All the examples are focused on relaying messages between clients, but in my case, in addition i want to create a bridge between socket.io and various other protocols (MQTT, flatbuf over serial, etc.)

Simple POC that would unblock me would be sending a message to a room on timer created from main context.

I'm happy to provide a simple example if you help me with understanding how to approach that.

**Comment by Totodore** [comment]
Hi ! 

The best way would be to have a cheaply clonable `io` struct that you could use to retrieve any socket/rooms. Currently it is not available. So the best way to do what you want is to build a shared `DashMap` or `Mutex<HashMap>` with an id as a key and the socket value. Thanks to that you would be able to have a socket ref everywhere : 


```rust
#[derive(Deserialize)]
struct Auth {
    pub mqtt_id: String,
}
use once_cell::sync::Lazy;

static SOCKS: Lazy<RwLock<HashMap<String, Weak<Socket<LocalAdapter>>>>> =
    Lazy::new(|| RwLock::new(HashMap::new()));

pub async fn handler(socket: Arc<Socket<LocalAdapter>>) {
    info!("Socket connected on / with id: {}", socket.sid);
    if let Ok(data) = socket.handshake.data::<Auth>() {
        info!("mqtt id: {:?}", &data.mqtt_id);
        SOCKS
            .write()
            .unwrap()
            .insert(data.mqtt_id, Arc::downgrade(&socket.clone()));
    } else {
        info!("No mqtt_id provided, disconnecting...");
        socket.disconnect().ok();
        return;
    }
```

Because the socket parameter is an `Arc<Socket>` you can clone it everywhere you want. However, there is currently one major drawback of doing that. If you keep the socket ref in your hashmap even when the socket is disconnected there will be a memory leak. And there is currently no `on_disconnect` handler so you can't remove the ref when the socket is disconnected (it is going to be available soon though).

So the only solution is to downgrade the `Arc` reference to a `Weak` reference in your hashmap so that when the socket is disconnected, the reference you own will allow the socket to be dropped.

I'll add another answer when the features needed for this kind of issue will be released.

**Comment by cr1tbit** [comment]
Thanks for the _extremely_ fast response :)

I achieved the thing I wanted, with your advice of using static hashmap. While not very elegant, it seems to be working for now. I'll update my code once we'll get that `io` struct you're talking about.

```rust
let debug_timer = every(5).seconds()
    .perform(|| async {
        //perform dead socket garbage collection
        SOCKS.write().unwrap().retain(|_, v| v.upgrade().is_some());
            
        for (k,v) in SOCKS.read().unwrap().iter() {
            if let Some(socket) = v.upgrade() {
                println!("send to socket {}", socket.sid);
                socket.emit("log", format!("timer for {}", socket.sid)).ok();
            } else {
                println!("socket {} is dead",k);
            }
        }
    });
spawn(debug_timer);
```

Have a nice evening.
